/* NB! Automatically generated by CoCoViLa, do not edit this file (it may be overwritten)*/

public class Nor {
    /*@ specification Nor {
        Or Or;
        Not Not;
        Not.in = Or.out;
    }@*/
}
